/**
 * EventPlan.jsx
 * 
 * Shown after the user completes the Survey or AI Chat flow.
 * Displays a COMPLETE event plan including:
 * - Venue recommendation
 * - Catering recommendation
 * - Decoration package
 * - Vendors (Photographer, DJ, Videographer)
 * - Total cost estimate and a match score
 * 
 * Each section card slides in from alternating sides using Framer Motion.
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/auth.store';
import {
    MapPin, Utensils, Sparkles, Camera,
    Star, CheckCircle, RefreshCw, Lock, Mail
} from 'lucide-react';
import { getEvent, getEventRecommendations } from '../services/planningService';

/** ─── Mock Full Plan Data ───────────────────────────────────────────────
 * In production this would be generated by the AI / backend based on
 * user survey inputs. The shape matches the documented EventPlan structure.
 */
const mockPlan = {
    venue: {
        name: "Kempinski Hotel Cairo",
        price: 45000,
        image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop",
        capacity: 300,
        type: "Ballroom"
    },
    catering: {
        name: "Gourmet Bites Catering",
        style: "Buffet",
        pricePerPerson: 500,
        guestCount: 80,
        menuHighlights: ["Grilled Salmon", "Mezze Station", "Live Pasta Bar", "Dessert Tower"]
    },
    decorations: {
        name: "Lumina Event Design",
        theme: "Modern Classic",
        colorPalette: ["#FFFFFF", "#D4AF37", "#1C1C1C"],
        includes: ["Uplighting", "Floral Arches", "Table Centrepieces", "Draping"],
        price: 15000
    },
    vendors: {
        photographer: { name: "Capture Moments Photography", price: 12000, rating: 4.9 },
        dj: { name: "DJ Pulse Cairo", price: 6000, rating: 4.8 },
        videographer: { name: "Cinematic Dreams Films", price: 15000, rating: 4.9 }
    },
    totalEstimate: 133000,
    matchScore: 94
};

/** ─── Section definitions for the plan cards ─────────────────────────── */
function buildSections(plan) {
    const cateringTotal = plan.catering.pricePerPerson * plan.catering.guestCount;
    return [
        {
            key: 'venue',
            label: 'Venue',
            icon: <MapPin className="w-5 h-5" />,
            color: 'purple',
            bg: 'bg-purple-50',
            border: 'border-purple-200',
            badge: 'bg-purple-600',
            image: plan.venue.image,
            title: plan.venue.name,
            sub: plan.venue.type,
            price: `${plan.venue.price.toLocaleString()} EGP`,
            tags: [`${plan.venue.capacity} guests`, plan.venue.type]
        },
        {
            key: 'catering',
            label: 'Catering',
            icon: <Utensils className="w-5 h-5" />,
            color: 'orange',
            bg: 'bg-orange-50',
            border: 'border-orange-200',
            badge: 'bg-orange-500',
            image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
            title: plan.catering.name,
            sub: plan.catering.style,
            price: `${cateringTotal.toLocaleString()} EGP (${plan.catering.pricePerPerson} × ${plan.catering.guestCount})`,
            tags: plan.catering.menuHighlights.slice(0, 3)
        },
        {
            key: 'decorations',
            label: 'Decorations',
            icon: <Sparkles className="w-5 h-5" />,
            color: 'pink',
            bg: 'bg-pink-50',
            border: 'border-pink-200',
            badge: 'bg-pink-500',
            image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&auto=format&fit=crop",
            title: plan.decorations.name,
            sub: plan.decorations.theme,
            price: `${plan.decorations.price.toLocaleString()} EGP`,
            tags: plan.decorations.includes.slice(0, 3)
        },
        {
            key: 'vendors',
            label: 'Vendors',
            icon: <Camera className="w-5 h-5" />,
            color: 'blue',
            bg: 'bg-blue-50',
            border: 'border-blue-200',
            badge: 'bg-blue-600',
            image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&auto=format&fit=crop",
            title: `${plan.vendors.photographer.name} + more`,
            sub: 'Photography · DJ · Video',
            price: `${(plan.vendors.photographer.price + plan.vendors.dj.price + plan.vendors.videographer.price).toLocaleString()} EGP`,
            tags: [
                `📸 ${plan.vendors.photographer.name.split(' ')[0]}`,
                `🎵 ${plan.vendors.dj.name}`,
                `🎬 Cinematic Films`
            ]
        }
    ];
}

export default function EventPlan() {
    const location = useLocation();
    const navigate = useNavigate();
    const { isAuthenticated } = useAuthStore();
    const eventIdFromState = location.state?.eventId;

    const [plan, setPlan] = useState(mockPlan);
    const [isLoading, setIsLoading] = useState(true);
    const sections = buildSections(plan);

    useEffect(() => {
        const fetchEventData = async () => {
            try {
                if (eventIdFromState) {
                    const { event, error: eventError } = await getEvent(eventIdFromState);

                    if (eventError) {
                        console.error('[EventPlan] Failed to fetch event:', eventError);
                    } else if (event) {
                        const { recommendations, error: recError } = await getEventRecommendations(event.id);

                        if (recError) {
                            console.error('[EventPlan] Failed to fetch recommendations:', recError);
                        }

                        // For now, still use mockPlan as recommendations backend is not yet fully integrated
                        // In future, build plan from recommendations data here
                    }
                }
            } catch (err) {
                console.error('[EventPlan] Unexpected error fetching event data:', err);
            } finally {
                const timer = setTimeout(() => setIsLoading(false), 600);
                return () => clearTimeout(timer);
            }
        };

        fetchEventData();
    }, [eventIdFromState]);


    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            style={{ maxWidth: '56rem', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '32px', paddingBottom: '16px' }}
        >
            {/* ─── Summary hero card ─── */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                style={{
                    background: 'linear-gradient(to bottom right, var(--aeva-ink), var(--aeva-ink-strong))',
                    color: 'var(--aeva-paper)',
                    padding: '32px',
                    borderRadius: 'var(--r-2xl)',
                    boxShadow: 'var(--shadow-lg)',
                    position: 'relative',
                    overflow: 'hidden'
                }}
            >
                {/* Decorative blobs */}
                <div style={{
                    position: 'absolute',
                    top: '-40px',
                    right: '-40px',
                    width: '160px',
                    height: '160px',
                    background: 'rgba(255,255,255,0.1)',
                    borderRadius: '50%',
                    filter: 'blur(64px)',
                    pointerEvents: 'none'
                }} />
                <div style={{
                    position: 'absolute',
                    bottom: '-40px',
                    left: '-40px',
                    width: '128px',
                    height: '128px',
                    background: 'rgba(255,255,255,0.1)',
                    borderRadius: '50%',
                    filter: 'blur(40px)',
                    pointerEvents: 'none'
                }} />

                <div style={{ position: 'relative', zIndex: 10 }}>
                    <p style={{ color: 'rgba(250,248,245,0.7)', fontSize: '12px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '8px' }}>Your Complete Event Plan</p>
                    <h1 style={{ fontSize: '32px', fontWeight: 700, marginBottom: '8px', color: 'var(--aeva-paper)' }}>Your Dream Event</h1>
                    <p style={{ color: 'rgba(250,248,245,0.8)', marginBottom: '24px' }}>Tailored to your preferences, budget, and style.</p>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '16px' }}>
                        {/* Match score */}
                        <div style={{
                          background: 'rgba(255,255,255,0.15)',
                          backdropFilter: 'blur(10px)',
                          borderRadius: 'var(--r-lg)',
                          padding: '16px',
                          textAlign: 'center'
                        }}>
                            <p style={{ fontSize: '24px', fontWeight: 700, color: 'var(--aeva-paper)' }}>{plan.matchScore}%</p>
                            <p style={{ fontSize: '12px', color: 'rgba(250,248,245,0.7)' }}>Match Score</p>
                        </div>
                        {/* Total estimate */}
                        <div style={{
                          background: 'rgba(255,255,255,0.15)',
                          backdropFilter: 'blur(10px)',
                          borderRadius: 'var(--r-lg)',
                          padding: '16px',
                          textAlign: 'center'
                        }}>
                            <p style={{ fontSize: '20px', fontWeight: 700, color: 'var(--aeva-paper)' }}>{plan.totalEstimate.toLocaleString()}</p>
                            <p style={{ fontSize: '12px', color: 'rgba(250,248,245,0.7)' }}>Est. Total (EGP)</p>
                        </div>
                        {/* Sections */}
                        <div style={{
                          background: 'rgba(255,255,255,0.15)',
                          backdropFilter: 'blur(10px)',
                          borderRadius: 'var(--r-lg)',
                          padding: '16px',
                          textAlign: 'center',
                          gridColumn: 'span 1'
                        }}>
                            <p style={{ fontSize: '20px', fontWeight: 700, color: 'var(--aeva-paper)' }}>4</p>
                            <p style={{ fontSize: '12px', color: 'rgba(250,248,245,0.7)' }}>Plan Sections</p>
                        </div>
                    </div>
                </div>
            </motion.div>

            {/* ─── Section cards, alternating slide-in ─── */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                {sections.map((section, i) => (
                    <PlanSectionCard
                        key={section.key}
                        section={section}
                        index={i}
                    />
                ))}
            </div>

            {/* ─── Lock In button ─── */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.8 }}
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '16px',
                    alignItems: 'flex-end',
                    justifyContent: 'flex-end',
                    paddingTop: '16px',
                    borderTop: '1px solid var(--aeva-line)'
                }}
            >
                <Link
                    to="/recommendations"
                    style={{
                        color: 'var(--aeva-ink-soft)',
                        textDecoration: 'none',
                        fontSize: '14px',
                        fontWeight: 500,
                        transition: 'color 200ms'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.color = 'var(--aeva-ink)'}
                    onMouseLeave={(e) => e.currentTarget.style.color = 'var(--aeva-ink-soft)'}
                >
                    ← Browse Venues Instead
                </Link>
                <button
                    onClick={() => {
                        if (!isAuthenticated) {
                            if (eventIdFromState) {
                                localStorage.setItem('aeva_pending_event_id', eventIdFromState);
                            }
                            navigate('/login', { state: { from: '/event-plan' } });
                        } else {
                            const resolvedEventId = eventIdFromState
                                || localStorage.getItem('aeva_pending_event_id');
                            localStorage.removeItem('aeva_pending_event_id');
                            navigate('/booking/confirm', { state: { eventId: resolvedEventId } });
                        }
                    }}
                    style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                        padding: '12px 32px',
                        borderRadius: 'var(--r-full)',
                        fontWeight: 700,
                        color: 'var(--aeva-paper)',
                        background: 'var(--aeva-ink)',
                        border: 'none',
                        boxShadow: 'var(--shadow-md)',
                        cursor: 'pointer',
                        transition: 'all 200ms'
                    }}
                    onMouseEnter={(e) => {
                        e.currentTarget.style.boxShadow = 'var(--shadow-lg)';
                        e.currentTarget.style.transform = 'translateY(-2px)';
                    }}
                    onMouseLeave={(e) => {
                        e.currentTarget.style.boxShadow = 'var(--shadow-md)';
                        e.currentTarget.style.transform = '';
                    }}
                >
                    <Lock className="w-5 h-5" /> Lock In This Plan
                </button>
            </motion.div>

        </motion.div>
    );
}

/** ─── Individual section card ─────────────────────────────────── */
function PlanSectionCard({ section, index }) {
    const xDir = index % 2 === 0 ? -40 : 40;

    return (
        <motion.div
            initial={{ opacity: 0, x: xDir }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.15 * index }}
            style={{
                background: 'var(--aeva-canvas)',
                borderRadius: 'var(--r-2xl)',
                boxShadow: 'var(--shadow-sm)',
                border: '1px solid var(--aeva-line)',
                overflow: 'hidden',
                display: 'flex',
                flexDirection: 'row',
                transition: 'box-shadow 300ms'
            }}
            onMouseEnter={(e) => e.currentTarget.style.boxShadow = 'var(--shadow-lg)'}
            onMouseLeave={(e) => e.currentTarget.style.boxShadow = 'var(--shadow-sm)'}
        >
            {/* Image */}
            <div style={{ width: '224px', height: '192px', overflow: 'hidden', flexShrink: 0 }}>
                <img
                    src={section.image}
                    alt={section.label}
                    style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                        transition: 'transform 500ms'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
                    onMouseLeave={(e) => e.currentTarget.style.transform = ''}
                />
            </div>

            {/* Content */}
            <div style={{ flex: 1, padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                <div>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
                        <span style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '6px',
                            padding: '4px 12px',
                            borderRadius: 'var(--r-full)',
                            fontSize: '12px',
                            fontWeight: 700,
                            color: 'var(--aeva-paper)',
                            background: 'var(--aeva-ink)'
                        }}>
                            {section.icon} {section.label}
                        </span>
                        <span style={{ fontSize: '18px', fontWeight: 700, color: 'var(--aeva-ink)' }}>{section.price}</span>
                    </div>
                    <h3 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--aeva-ink)', marginBottom: '8px' }}>{section.title}</h3>
                    <p style={{ fontSize: '14px', color: 'var(--aeva-ink-soft)', marginBottom: '12px' }}>{section.sub}</p>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                        {section.tags.map(tag => (
                            <span key={tag} style={{
                                fontSize: '12px',
                                padding: '4px 8px',
                                borderRadius: 'var(--r-md)',
                                background: 'var(--aeva-paper-warm)',
                                color: 'var(--aeva-ink)',
                                border: '1px solid var(--aeva-line)'
                            }}>
                                {tag}
                            </span>
                        ))}
                    </div>
                </div>

                {/* Swap button */}
                <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '16px' }}>
                    <button style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '6px',
                        fontSize: '14px',
                        color: 'var(--aeva-ink-soft)',
                        background: 'none',
                        border: 'none',
                        cursor: 'pointer',
                        fontWeight: 500,
                        transition: 'color 200ms'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.color = 'var(--aeva-ink)'}
                    onMouseLeave={(e) => e.currentTarget.style.color = 'var(--aeva-ink-soft)'}
                    >
                        <RefreshCw className="w-4 h-4" /> Swap
                    </button>
                </div>
            </div>
        </motion.div>
    );
}
