/**
 * EventPlan.jsx
 * 
 * Shown after the user completes the Survey or AI Chat flow.
 * Displays a COMPLETE event plan including:
 * - Venue recommendation
 * - Catering recommendation
 * - Decoration package
 * - Vendors (Photographer, DJ, Videographer)
 * - Total cost estimate and a match score
 * 
 * Each section card slides in from alternating sides using Framer Motion.
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/auth.store';
import {
    MapPin, Utensils, Sparkles, Camera,
    Star, CheckCircle, RefreshCw, Lock, Mail
} from 'lucide-react';
import { getEvent } from '../services/planningService';
import { getEventRecommendations } from '../services/aiService';
import { supabase } from '../lib/supabaseClient';

/** ─── Mock Full Plan Data ───────────────────────────────────────────────
 * In production this would be generated by the AI / backend based on
 * user survey inputs. The shape matches the documented EventPlan structure.
 */
const mockPlan = {
    venue: {
        name: "Kempinski Hotel Cairo",
        price: 45000,
        image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop",
        capacity: 300,
        type: "Ballroom"
    },
    catering: {
        name: "Gourmet Bites Catering",
        style: "Buffet",
        pricePerPerson: 500,
        guestCount: 80,
        menuHighlights: ["Grilled Salmon", "Mezze Station", "Live Pasta Bar", "Dessert Tower"]
    },
    decorations: {
        name: "Lumina Event Design",
        theme: "Modern Classic",
        colorPalette: ["#FFFFFF", "#D4AF37", "#1C1C1C"],
        includes: ["Uplighting", "Floral Arches", "Table Centrepieces", "Draping"],
        price: 15000
    },
    vendors: {
        photographer: { name: "Capture Moments Photography", price: 12000, rating: 4.9 },
        dj: { name: "DJ Pulse Cairo", price: 6000, rating: 4.8 },
        videographer: { name: "Cinematic Dreams Films", price: 15000, rating: 4.9 }
    },
    totalEstimate: 133000,
    matchScore: 94
};

/** ─── Section definitions for the plan cards ─────────────────────────── */
function buildSections(plan) {
    const cateringTotal = plan.catering.pricePerPerson * plan.catering.guestCount;
    return [
        {
            key: 'venue',
            label: 'Venue',
            icon: <MapPin className="w-5 h-5" />,
            color: 'purple',
            bg: 'bg-purple-50',
            border: 'border-purple-200',
            badge: 'bg-purple-600',
            image: plan.venue.image,
            title: plan.venue.name,
            sub: plan.venue.type,
            price: `${plan.venue.price.toLocaleString()} EGP`,
            tags: [`${plan.venue.capacity} guests`, plan.venue.type]
        },
        {
            key: 'catering',
            label: 'Catering',
            icon: <Utensils className="w-5 h-5" />,
            color: 'orange',
            bg: 'bg-orange-50',
            border: 'border-orange-200',
            badge: 'bg-orange-500',
            image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
            title: plan.catering.name,
            sub: plan.catering.style,
            price: `${cateringTotal.toLocaleString()} EGP (${plan.catering.pricePerPerson} × ${plan.catering.guestCount})`,
            tags: plan.catering.menuHighlights.slice(0, 3)
        },
        {
            key: 'decorations',
            label: 'Decorations',
            icon: <Sparkles className="w-5 h-5" />,
            color: 'pink',
            bg: 'bg-pink-50',
            border: 'border-pink-200',
            badge: 'bg-pink-500',
            image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&auto=format&fit=crop",
            title: plan.decorations.name,
            sub: plan.decorations.theme,
            price: `${plan.decorations.price.toLocaleString()} EGP`,
            tags: plan.decorations.includes.slice(0, 3)
        },
        {
            key: 'vendors',
            label: 'Vendors',
            icon: <Camera className="w-5 h-5" />,
            color: 'blue',
            bg: 'bg-blue-50',
            border: 'border-blue-200',
            badge: 'bg-blue-600',
            image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&auto=format&fit=crop",
            title: `${plan.vendors.photographer.name} + more`,
            sub: 'Photography · DJ · Video',
            price: `${(plan.vendors.photographer.price + plan.vendors.dj.price + plan.vendors.videographer.price).toLocaleString()} EGP`,
            tags: [
                `📸 ${plan.vendors.photographer.name.split(' ')[0]}`,
                `🎵 ${plan.vendors.dj.name}`,
                `🎬 Cinematic Films`
            ]
        }
    ];
}

export default function EventPlan() {
    const location = useLocation();
    const navigate = useNavigate();
    const { isAuthenticated } = useAuthStore();
    const eventIdFromState = location.state?.eventId;

    const [plan, setPlan] = useState(mockPlan);
    const [isLoading, setIsLoading] = useState(true);
    const sections = buildSections(plan);

    useEffect(() => {
        const fetchEventData = async () => {
            const resolvedId = eventIdFromState || localStorage.getItem('aeva_pending_event_id');
            try {
                if (resolvedId) {
                    const { event, error: eventError } = await getEvent(resolvedId);

                    if (eventError) {
                        console.error('[EventPlan] Failed to fetch event:', eventError);
                    } else if (event) {
                        const { venueRecommendation } = await getEventRecommendations(event.id);

                        if (venueRecommendation) {
                            try {
                                const { data: venueData } = await supabase
                                    .from('venues')
                                    .select('*')
                                    .eq('id', venueRecommendation.entity_id)
                                    .single();

                                if (venueData) {
                                    const img = Array.isArray(venueData.image_urls)
                                        ? venueData.image_urls[0]
                                        : (JSON.parse(venueData.image_urls || '[]')[0] || mockPlan.venue.image);
                                    setPlan(prev => ({
                                        ...prev,
                                        venue: {
                                            ...prev.venue,
                                            name: venueData.name,
                                            price: venueData.price_min || prev.venue.price,
                                            type: venueData.venue_type || prev.venue.type,
                                            capacity: venueData.capacity_max || prev.venue.capacity,
                                            image: img
                                        },
                                        matchScore: Math.round(venueRecommendation.score || prev.matchScore)
                                    }));
                                }
                            } catch (venueErr) {
                                console.warn('[EventPlan] Error fetching venue details:', venueErr);
                            }
                        }
                    }
                }
            } catch (err) {
                console.error('[EventPlan] Unexpected error fetching event data:', err);
            } finally {
                const timer = setTimeout(() => setIsLoading(false), 600);
                return () => clearTimeout(timer);
            }
        };

        fetchEventData();
    }, [eventIdFromState]);


    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="max-w-4xl mx-auto space-y-8 py-4"
        >
            {/* ─── Summary hero card ─── */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="bg-gradient-to-br from-[#6B3FF3] to-[#a855f7] text-white p-8 rounded-[2rem] shadow-xl relative overflow-hidden"
            >
                {/* Decorative blobs */}
                <div className="absolute -top-10 -right-10 w-40 h-40 bg-white/10 rounded-full blur-2xl pointer-events-none" />
                <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-white/10 rounded-full blur-xl pointer-events-none" />

                <div className="relative z-10">
                    <p className="text-white/70 text-sm font-medium uppercase tracking-widest mb-2">Your Complete Event Plan</p>
                    <h1 className="text-4xl font-display font-bold mb-1">Your Dream Event</h1>
                    <p className="text-white/80 mb-6">Tailored to your preferences, budget, and style.</p>

                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                        {/* Match score */}
                        <div className="bg-white/15 backdrop-blur rounded-2xl p-4 text-center">
                            <p className="text-3xl font-bold">{plan.matchScore}%</p>
                            <p className="text-sm text-white/70">Match Score</p>
                        </div>
                        {/* Total estimate */}
                        <div className="bg-white/15 backdrop-blur rounded-2xl p-4 text-center">
                            <p className="text-2xl font-bold">{plan.totalEstimate.toLocaleString()}</p>
                            <p className="text-sm text-white/70">Est. Total (EGP)</p>
                        </div>
                        {/* Sections */}
                        <div className="bg-white/15 backdrop-blur rounded-2xl p-4 text-center col-span-2 md:col-span-1">
                            <p className="text-2xl font-bold">4</p>
                            <p className="text-sm text-white/70">Plan Sections</p>
                        </div>
                    </div>
                </div>
            </motion.div>

            {/* ─── Section cards, alternating slide-in ─── */}
            <div className="space-y-6">
                {sections.map((section, i) => (
                    <PlanSectionCard
                        key={section.key}
                        section={section}
                        index={i}
                    />
                ))}
            </div>

            {/* ─── Lock In button ─── */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.8 }}
                className="flex flex-col sm:flex-row gap-4 items-center justify-end pt-4 border-t border-gray-100"
            >
                <Link
                    to="/recommendations"
                    className="text-text-muted hover:text-primary transition-colors text-sm font-medium"
                >
                    ← Browse Venues Instead
                </Link>
                <button
                    onClick={() => {
                        if (!isAuthenticated) {
                            // Save eventId before login redirect so it survives the auth flow
                            if (eventIdFromState) {
                                localStorage.setItem('aeva_pending_event_id', eventIdFromState);
                            }
                            navigate('/login', { state: { from: '/event-plan' } });
                        } else {
                            // Use eventId from state, or fall back to localStorage if returning from login
                            const resolvedEventId = eventIdFromState
                                || localStorage.getItem('aeva_pending_event_id');
                            localStorage.removeItem('aeva_pending_event_id');
                            navigate('/booking/confirm', { state: { eventId: resolvedEventId } });
                        }
                    }}
                    className="flex items-center gap-2 px-8 py-3 rounded-full font-bold text-white shadow-lg transition-all bg-gradient-to-r from-[#6B3FF3] to-[#a855f7] hover:shadow-purple-300 hover:scale-105"
                >
                    <Lock className="w-5 h-5" /> Lock In This Plan
                </button>
            </motion.div>

        </motion.div>
    );
}

/** ─── Individual section card ─────────────────────────────────── */
function PlanSectionCard({ section, index }) {
    // Alternating slide-in direction: even = left, odd = right
    const xDir = index % 2 === 0 ? -40 : 40;

    return (
        <motion.div
            initial={{ opacity: 0, x: xDir }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.15 * index }}
            className={`bg-white rounded-[2rem] shadow-sm border ${section.border} overflow-hidden flex flex-col md:flex-row group hover:shadow-xl transition-shadow duration-300`}
        >
            {/* Image */}
            <div className="md:w-56 h-48 md:h-auto overflow-hidden flex-shrink-0">
                <img
                    src={section.image}
                    alt={section.label}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
            </div>

            {/* Content */}
            <div className="flex-1 p-6 flex flex-col justify-between">
                <div>
                    <div className="flex items-center justify-between mb-3">
                        <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold text-white ${section.badge}`}>
                            {section.icon} {section.label}
                        </span>
                        <span className="text-lg font-bold text-text-dark">{section.price}</span>
                    </div>
                    <h3 className="text-xl font-bold font-display text-text-dark mb-1">{section.title}</h3>
                    <p className="text-sm text-text-muted mb-3">{section.sub}</p>
                    <div className="flex flex-wrap gap-2">
                        {section.tags.map(tag => (
                            <span key={tag} className={`text-xs px-2 py-1 rounded-md ${section.bg} text-gray-700 border ${section.border}`}>
                                {tag}
                            </span>
                        ))}
                    </div>
                </div>

                {/* Swap button */}
                <div className="flex justify-end mt-4">
                    {/* TODO: Enable after backend migration */}
                    <button className="flex items-center gap-1.5 text-sm text-text-muted hover:text-primary transition-colors font-medium">
                        <RefreshCw className="w-4 h-4" /> Swap
                    </button>
                </div>
            </div>
        </motion.div>
    );
}
